### ISSUE TITLE
Report generation fails

### ISSUE THREAD

**Issue by brentzundel** [w3c/vc-test-suite#28] opened 2019-05-21 21:01 UTC
This is my terminal output when trying to run the report:

> brent@Lappy2000:~/dev/w3c/vc-test-suite$ npm run report
> 
> vc-test-suite@0.3.0 report /home/brent/dev/w3c/vc-test-suite
> mocha --recursive test/vc-data-model-1.0/ -R json > implementations/report.json
> 
> 
> npm ERR! Linux 4.15.0-50-generic
> npm ERR! argv "/usr/bin/node" "/usr/bin/npm" "run" "report"
> npm ERR! node v8.10.0
> npm ERR! npm  v3.5.2
> npm ERR! code ELIFECYCLE
> npm ERR! vc-test-suite@0.3.0 report: `mocha --recursive test/vc-data-model-1.0/ -R json > implementations/report.json`
> npm ERR! Exit status 8
> npm ERR! 
> npm ERR! Failed at the vc-test-suite@0.3.0 report script 'mocha --recursive test/vc-data-model-1.0/ -R json > implementations/report.json'.
> npm ERR! Make sure you have the latest version of node.js and npm installed.
> npm ERR! If you do, this is most likely a problem with the vc-test-suite package,
> npm ERR! not with npm itself.
> npm ERR! Tell the author that this fails on your system:
> npm ERR!     mocha --recursive test/vc-data-model-1.0/ -R json > implementations/report.json
> npm ERR! You can get information on how to open an issue for this project with:
> npm ERR!     npm bugs vc-test-suite
> npm ERR! Or if that isn't available, you can get their info via:
> npm ERR!     npm owner ls vc-test-suite
> npm ERR! There is likely additional logging output above.
> 
> npm ERR! Please include the following file with any support request:
> npm ERR!     /home/brent/dev/w3c/vc-test-suite/npm-debug.log

I was able to directly run the command:
`mocha --recursive test/vc-data-model-1.0/ "--timeout" "30000" -R json > implementations/report.json`

**Comment by dmitrizagidulin** [comment] 2019-05-23 15:24
@brentzundel Do you know why it failed via `npm run test`? Was it a timeout issue?

**Comment by brentzundel** [comment] 2019-05-23 17:08
My assumption was that is was a timeout issue, because running the mocha command directly (with the timeout included) worked fine. But when I run the command:
`mocha --recursive test/vc-data-model-1.0/ -R json > implementations/report.json`
it also works fine. So now I'm not sure.

**Comment by yancyribbens** [comment] 2019-05-29 16:03
Confirmed report generation fails for me as well but worked fine when running `mocha --recursive test/vc-data-model-1.0/ -R json > implementations/report.json`

**Comment by dmitrizagidulin** [comment] 2019-06-25 14:46
Next steps: @dmitrizagidulin cannot reproduce, need to coordinate with @yancyribbens or @brentzundel to help debug.

**Comment by dmitrizagidulin** [comment] 2019-07-02 13:07
Addressed in PR #66 (to avoid confusion, the README instructions now direct devs to use the `mocha` command directly instead of the `npm` script).
Closing.

**Closed as completed by dmitrizagidulin** 2019-07-02 13:07 UTC
Labels: bug
